name: satari_pos
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^3.4.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  formz: ^0.4.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  internet_connection_checker: ^1.0.0+1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  syncfusion_flutter_datepicker: ^20.4.42

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg_picture/
    - bloc_logo_small.png
