// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvsqFjeTUuwO_8cC3Tpb_soxHzfFqW39A',
    appId: '1:769165278290:web:d361e6834acc0697aeb38b',
    messagingSenderId: '769165278290',
    projectId: 'sataripos',
    authDomain: 'sataripos.firebaseapp.com',
    storageBucket: 'sataripos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_meIC86bSjQ-zsT-OldHzs30ovZYswAY',
    appId: '1:769165278290:android:38d60ccfe3d74945aeb38b',
    messagingSenderId: '769165278290',
    projectId: 'sataripos',
    storageBucket: 'sataripos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFHckVg9YhdnsEHniv7vp0z7TXnh-pQ7g',
    appId: '1:769165278290:ios:b833bbf8f00f727aaeb38b',
    messagingSenderId: '769165278290',
    projectId: 'sataripos',
    storageBucket: 'sataripos.appspot.com',
    iosClientId: '769165278290-63s7tnm3osjnk2uo52oemri7aoerd8qu.apps.googleusercontent.com',
    iosBundleId: 'satariPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFHckVg9YhdnsEHniv7vp0z7TXnh-pQ7g',
    appId: '1:769165278290:ios:814985ab1826c980aeb38b',
    messagingSenderId: '769165278290',
    projectId: 'sataripos',
    storageBucket: 'sataripos.appspot.com',
    iosClientId: '769165278290-77rah97qsbsofgqcrh7n6mnaa1ojqs61.apps.googleusercontent.com',
    iosBundleId: 'com.example.satariPos',
  );
}
